server:
  port: 8081  # ✅ Change-le si besoin (par exemple si 8080 est occupé)

spring:

  application:
    name: business-service  # ✅ Tu peux modifier le nom selon ton microservice

  datasource:
    url: jdbc:postgresql://localhost:5432/db_business
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    discovery:
      enabled: true
    config:
      enabled: true

  data:
    rest:
      base-path: /api

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, refresh

aws:
  s3:
    access: AKIA5DY72EPB6LUERMLD
    secret: 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
    region: eu-north-1
    bucket: roots-business

# 🔐 Si tu utilises Keycloak, décommente et configure la section suivante :
# security:
#   oauth2:
#     resourceserver:
#       jwt:
#         issuer-uri: http://localhost:9090/realms/gp-app
